import { model } from 'mongoose';

const PRODUCTS = [
  {
    brand: 'Air Bar',
    model: 'Mini',
    puffs: 2000,
    min_price: 700,
    suggested_price: 900,
    image: '/images/air-bar-mini.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Fruit Cereal',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Mango Bliss',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'I Play',
    model: 'Max',
    puffs: 2500,
    min_price: 500,
    suggested_price: 600,
    image: '/images/i-play-max.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Blueberry Cherry',
        color: 'red',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
      {
        name: 'Berry Watermelon',
        color: 'pink',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
      {
        name: 'Pineapple Coconut',
        color: 'orange',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
      {
        name: 'Banana Ice',
        color: 'yellow',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
      {
        name: 'Sour Raspberry',
        color: 'fuchsia',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
      {
        name: 'Mixed Berries Lemon',
        color: 'purple',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
      {
        name: 'Blue Raz Lemon',
        color: 'blue',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
      {
        name: 'Energy Water Ice',
        color: 'cyan',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
      {
        name: 'Lush Ice',
        color: 'orange',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Esco Bars',
    model: 'Kilo',
    puffs: 4000,
    min_price: 400,
    suggested_price: 400,
    image: '/images/esco-bars-kilo.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Mango Twist',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: true,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'North',
    model: '5000',
    puffs: 5000,
    min_price: 800,
    suggested_price: 1100,
    image: '/images/north-5000.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Lost Mary',
    model: 'OS5000',
    puffs: 5000,
    min_price: 800,
    suggested_price: 1000,
    image: '/images/lost-mary-os5000.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Strawberry Banana',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Berry Pasion Fruit Grape',
        color: 'fuchsia',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Watermelon Kiwi Lemonade',
        color: 'blue',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Rose Sour Plum Mint',
        color: 'pink',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Raspberry Lemonade',
        color: 'purple',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Tyson',
    model: 'Lightweight 3Pack',
    puffs: 6000,
    min_price: 1000,
    suggested_price: 1300,
    image: '/images/tyson-lightweight-3pack.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Watermelon',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Cool Mint, Frozen Banana, Green Apple',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Frozen Bleberry',
        color: 'fuchsia',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Grape Razz',
        color: 'purple',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Enoubar',
    model: '6000',
    puffs: 6000,
    min_price: 600,
    suggested_price: 600,
    image: '/images/enoubar-6000.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Sakura Grape',
        color: 'purple',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Mango Peach Ice',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Strawberry Orange Mint',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'strawberry Mango',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Pina Colada',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: true,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'I Play',
    model: 'Bang',
    puffs: 6000,
    min_price: 700,
    suggested_price: 1000,
    image: '/images/i-play-bang.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Cool Mint',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Watermelon',
        color: 'pink',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Aloe Grape',
        color: 'purple',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Pineapple Coconut',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Energy Ice',
        color: 'cyan',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: true,
    like_count: 0,
    available: true,
  },
  {
    brand: 'I Play',
    model: 'Ulix',
    puffs: 6000,
    min_price: 700,
    suggested_price: 1000,
    image: '/images/i-play-ulix.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Cranberry Grape',
        color: 'purple',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Blackcurrant Mint',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Cool Mint',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'I Play',
    model: 'Ecco',
    puffs: 7000,
    min_price: 800,
    suggested_price: 1100,
    image: '/images/i-play-ecco.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Grapefruit Aloe',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Grape Pear',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Ice Water',
        color: 'cyan',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Bugatti',
    model: 'Spaceship',
    puffs: 7000,
    min_price: 600,
    suggested_price: 600,
    image: '/images/bugatti-spaceship.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Orange Cush',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Blue Gummy',
        color: 'blue',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Menthol',
        color: 'cyan',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Cherry Cola',
        color: 'red',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Frozen Pineapple',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Creamy Tobacco',
        color: 'neutral',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Double Mint',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: true,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Moti',
    model: 'Play Bar',
    puffs: 7500,
    min_price: 700,
    suggested_price: 900,
    image: '/images/moti-play-bar.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Pineapple Mango',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Lush Ice',
        color: 'pink',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Watermelon Bubblegum',
        color: 'fuchsia',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Miami Mint',
        color: 'cyan',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Crown Bar',
    model: 'Pro 8000',
    puffs: 8000,
    min_price: 1500,
    suggested_price: 2000,
    image: '/images/crown-bar-pro-8000.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Two Apple',
        color: 'red',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Orange Mint',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Vapesring',
    model: 'Bar 8000',
    puffs: 8000,
    min_price: 850,
    suggested_price: 1100,
    image: '/images/vapesring-bar-8000.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Humo Azul',
    model: '8000',
    puffs: 8000,
    min_price: 1000,
    suggested_price: 1300,
    image: '/images/humo-azul-8000.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Peach Mango Pineapple',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Peach Cobler',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Strawberry Watermelon Grape Ice',
        color: 'red',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Watermelon',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Icewave',
    model: 'X8500',
    puffs: 8500,
    min_price: 1000,
    suggested_price: 1300,
    image: '/images/icewave-x8500.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Peach Ice',
        color: 'pink',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Strawberry Ice Cream',
        color: 'red',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Blue Razz Ice',
        color: 'blue',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Ribena',
        color: 'purple',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Cherry Cola',
        color: 'Orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: true,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Lost Vape',
    model: 'Orion Bar',
    puffs: 10000,
    min_price: 1200,
    suggested_price: 1500,
    image: '/images/lost-vape-orion-bar.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Strawberry Summertime',
        color: 'fuchsia',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Raspberry Sour Apple',
        color: 'purple',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Pineapple Lemonade',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Strawberry Chew',
        color: 'pink',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'I Play',
    model: 'Cloud Pro',
    puffs: 12000,
    min_price: 1000,
    suggested_price: 1200,
    image: '/images/i-play-cloud-pro.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Pina Coconut',
        color: 'neutral',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Sour Apple',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Summer Slushie',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Watermelon',
        color: 'pink',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Berries Cherry',
        color: 'purple',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Grape Strawberry',
        color: 'fuchsia',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Tropical Fruits',
        color: 'neutral',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'North',
    model: 'Vision',
    puffs: 15000,
    min_price: 1000,
    suggested_price: 1300,
    image: '/images/north-vision.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Strawberry Mango',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Mighty Mint',
        color: 'cyan',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Blue Slurpie',
        color: 'blue',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Grape Blow Pop',
        color: 'purple',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Mango Dragon Fruit',
        color: 'fuchsia',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Tropical Rainbow Blast',
        color: 'pink',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Blueberry Watermelon',
        color: 'purple',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Lost Mary',
    model: 'Turbo',
    puffs: 15000,
    min_price: 1200,
    suggested_price: 1500,
    image: '/images/lost-mary-turbo.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Dr.Cherry',
        color: 'red',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Strawberry Orange',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Raspberry Banana',
        color: 'red',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Nana Coconut',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Grapefruit Berries',
        color: 'fuchsia',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Peach+',
        color: 'red',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Geek Bar',
    model: 'Pulse',
    puffs: 15000,
    min_price: 1200,
    suggested_price: 1500,
    image: '/images/geek-bar-pulse.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Elux',
    model: 'Cyberover',
    puffs: 18000,
    min_price: 1300,
    suggested_price: 1600,
    image: '/images/elux-cyberover.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Lost Cherry',
        color: 'red',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Red Bomb',
        color: 'red',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Vfeel',
    model: 'PI20000',
    puffs: 20000,
    min_price: 1200,
    suggested_price: 1500,
    image: '/images/vfeel-pi20000.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Grape Ice',
        color: 'purple',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Kiwi Passion Fruit Guava',
        color: 'blue',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Cherry Cola',
        color: 'neutral',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Lemon Mint',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: true,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Fifty Bar',
    model: '20000',
    puffs: 20000,
    min_price: 1500,
    suggested_price: 1800,
    image: '/images/fifty-bar-20000.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Gold Tobacco',
        color: 'neutral',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Vanilla Bean Tobacco',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Lost Mary',
    model: 'MO20000 PRO',
    puffs: 20000,
    min_price: 2000,
    suggested_price: 2500,
    image: '/images/lost-mary-mo20000-pro.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Pear Drop',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Pure',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Lime Grapefruit',
        color: 'cyan',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Orange Pomegranate Cranberry',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Red Wave',
        color: 'red',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: true,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Tyson',
    model: 'Legend',
    puffs: 30000,
    min_price: 2500,
    suggested_price: 3000,
    image: '/images/tyson-legend.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Apple Melonberry',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Frozen Strawberry',
        color: 'purple',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Frozen Mango',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Watermelon',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Waka',
    model: 'soPro Titan',
    puffs: 30000,
    min_price: 1500,
    suggested_price: 1700,
    image: '/images/waka_sopro_titan.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Strawberry Mango Ice',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Strawberry Kiwi Ice',
        color: 'red',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Banana Berry Ice',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Cherry Soda Ice',
        color: 'Purple',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Pillow Talk',
    model: 'IC/NC40000',
    puffs: 40000,
    min_price: 2500,
    suggested_price: 3000,
    image: '/images/pillow-talk-icnc40000.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Mexican Mango',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Grape B-Pop',
        color: 'fuchsia',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Craazzyy Melon',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Cherry Lemon',
        color: 'pink',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Peach Lemon Gummies',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Sour Apple Ice',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Pink Lemonade',
        color: 'pink',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Orange Creamksicle',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Virginia Tobacco',
        color: 'neutral',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: true,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Adjust',
    model: 'MyFlavor',
    puffs: 40000,
    min_price: 1800,
    suggested_price: 2200,
    image: '/images/adjust-myflavor.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Watermelon B Pop',
        color: 'red',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Strawberry Banana',
        color: 'pink',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Adjust',
    model: 'MyCool',
    puffs: 40000,
    min_price: 1800,
    suggested_price: 2200,
    image: '/images/adjust-mycool.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Airmez',
    model: 'XBeats',
    puffs: 40000,
    min_price: 2000,
    suggested_price: 2500,
    image: '/images/airmez-xbeats.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Miami Mint',
        color: 'yellow',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Sour Fucking Fab',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Sour Mango Pineapple',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Raspberry Peach Lime',
        color: 'purple',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Banana Taffy Freeze',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: true,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Flavor Beast',
    model: 'XBM50',
    puffs: 50000,
    min_price: 2200,
    suggested_price: 3000,
    image: '/images/flavor-beast-xbm50.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Packin Peach Berry',
        color: 'red',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Orange Soda',
        color: 'orange',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Lemon Lime Soda',
        color: 'green',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Fucking Fab',
        color: 'purple',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
      {
        name: 'Ginger Ale',
        color: 'red',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Smookah',
    model: 'E-Hookah Head',
    puffs: 100000,
    min_price: 5000,
    suggested_price: 6000,
    image: '/images/smookah-e-hookah-head.png',
    description: '',
    category: 'Disposable Nicotine Vape',
    kind: 'NicDisposable',
    flavors: [
      {
        name: 'Blueberry',
        color: 'blue',
        available_location: {
          store_6: { available: false, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: false, quantity: 0 },
        },
      },
    ],
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
  },
  {
    brand: 'Budget',
    model: 'Disposable Vape',
    min_price: 1800,
    suggested_price: 2000,
    image: '/images/budget-disposable-vape.png',
    description: '',
    category: 'Disposable HHC Vape',
    kind: 'HHCDisposable',
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
    grams: 1,
    components: {
      hhc: true,
    },
    strains: [
      {
        name: 'Hybrid',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
      {
        name: 'Indica',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
      {
        name: 'Sativa',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
    ],
    flavors: [
      {
        name: 'Sweet Tsunami',
        color: 'blue',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
      {
        name: 'Watermelon Zkittlez',
        color: 'red',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
      {
        name: 'Papaya Kush',
        color: 'orange',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
    ],
  },
  {
    brand: 'Exotic',
    model: 'Gummies 50mg',
    min_price: 200,
    suggested_price: 400,
    image: '/images/gummies-50mg.png',
    description: '',
    category: 'Edible',
    kind: 'Edible',
    on_sale: false,
    on_featured: false,
    like_count: 0,
    available: true,
    servings: 1,
    dosage_mg: 50,
    flavors: [
      {
        name: 'Mango',
        color: 'orange',
        available_location: {
          store_6: { available: true, quantity: 0 },
          store_22: { available: true, quantity: 0 },
          store_28: { available: true, quantity: 0 },
        },
      },
    ],
    components: {
      d8: true,
    },
  },
];

export default PRODUCTS;
